### ISSUE TITLE
rtl8821au freezes the kernel 3.19.0-32-generic

### ISSUE THREAD

**Issue by grampsit** [Grawp/rtl8812au_rtl8821au#13]
I downloaded the current version of rtl8812au_rtl8821au (as of April 2 ) to a newly installed Linux Mint 17.3 system (OS: Linux 3.19.0-32-generic #37~14.04.1-Ubuntu SMP. HW: Medion P2120 desktop). After compiling the driver ("make") and installing it ("make install") the OS was seriously sick. Exactly 1 times the driver worked fine. After that, the system freezed each time around the initial login after bootstrap.  I needed a live CD system to uninstall the 8812au.ko module and to restore the dependencies. Then, the system was okay again. I'm prepared to do a bit testing and reporting with forthcoming versions because I suppose that this hardware is not in the reach of @Grawp.
 BTW, a minor problem in the Makefile needs a fix. The compiler exits with error because of an unknown option: "-Werror=incompatible-pointer-types".

**Comment by Grawp** [comment]
3.19 kernel is rather old. I'm focusing just on newer kernels & Archlinux.
If your GCC doesn't recognize `-Werror=incompatible-pointer-types` then your GCC is rather old as well. It's closed issue #1

**Comment by grampsit** [comment]
Thanks for the response. The unhappy thing is that kernel 3.19 and gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1) are the current ones distributed with Mint Linux 17.3. Anyway, meanwhile I've found a working driver for my system on github (fredy72/rtl8821au.git) which might also help others.
