### ISSUE TITLE
Make error with Makefile and usb_intf.c

### ISSUE THREAD

**Issue by M1k3CrU2** [Grawp/rtl8812au_rtl8821au#25]
New to Linux, using centOS 7 kernel version 3.10.0-327.28.3.el7.x86_64.
I'm also using the edimax 7811utc usb as well, and also still get errors with the changes AndyPi made.

The first text file is just the original without AndyPi's changes:
[originalerror.txt](https://github.com/Grawp/rtl8812au_rtl8821au/files/450695/originalerror.txt)

The following text files are the ones with AndyPi's changes:
[1_1-3error.txt](https://github.com/Grawp/rtl8812au_rtl8821au/files/450696/1_1-3error.txt)
[1-2_2-3_2_allerror.txt](https://github.com/Grawp/rtl8812au_rtl8821au/files/450697/1-2_2-3_2_allerror.txt)
[3error.txt](https://github.com/Grawp/rtl8812au_rtl8821au/files/450698/3error.txt)

The naming convention behind this is to let you know which changes I did in order to get that error.
1 is the first Makefile change
2 is the second Makefile change
3 is the usb_intf.c change
all means all changes
The dashes are for which changes I did at the time of making, and underscores separate those make instances.

**Comment by Grawp** [comment]
I'm sorry. I don't want to support such archaic kernel or even gcc < 6.0. I think I should make a disclaimer somewhere that this repo is primarily for Archlinux.
