### ISSUE TITLE
XHCI_TRUST_TX_LENGTH quirk

### ISSUE THREAD

**Issue by terencode** [Grawp/rtl8812au_rtl8821au#28]
Using the AUR package with the TP LINK T4U, I first have to say it seems to be working great: no problem switching between 2.4GHz and 5GHz bands, connection is stable, no apparent loss in any kind.
However, looking at dmesg, I got lot's of spamming:

>[...]
sept. 24 19:43:47 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:47 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:47 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:48 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:48 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:48 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:48 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:48 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:48 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:49 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:52 terence-arch kernel: handle_tx_event: 26 callbacks suppressed
sept. 24 19:43:52 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:52 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:52 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:52 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:53 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:53 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:54 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:54 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:54 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
sept. 24 19:43:54 terence-arch kernel: xhci_hcd 0000:07:00.0: WARN Successful completion on short TX: needs XHCI_TRUST_TX_LENGTH quirk?
>[...]

I first made sure it was coming from the adapter, tried changing it to different 3.0 usb ports but nothing changed.

*Arch Linux x86_64 Linux 4.7.4-1-ARCH*

**Comment by Thoma5** [comment]
Same device and same kernel, on usb 3.0 too, and I have nothing like that in my dmesg output.

**Comment by terencode** [comment]
Ok,  any idea to figure out the problem? 
It's not doing that if I keep the adapter connected but disable the WiFi

**Comment by Thoma5** [comment]
It's a problem with your usb 3.0 controller driver. 
If your contollers device id is 1042 (Check with lspci -nn )  see:
https://github.com/torvalds/linux/commit/2391eacbd00b706ff4902db7dbee21e33b6f1850 
https://github.com/torvalds/linux/blob/master/drivers/usb/host/xhci.h#L1650-L1651 
You could try to add 
`xhci->quirks |= XHCI_TRUST_TX_LENGTH;` right above line https://github.com/torvalds/linux/blob/master/drivers/usb/host/xhci-pci.c#L191 and compile your own kernel patch using ABS(see the arch wiki).

**Comment by terencode** [comment]
My controller id is indeed 1042.
I thought I already checked usb 2.0 ports but after trying again there is no more spam.
Shouldn't this fix be already effective?

**Comment by Thoma5** [comment]
No, I don't think so, since for ETRON they have 
```		xhci->quirks |= XHCI_RESET_ON_RESUME;
		xhci->quirks |= XHCI_TRUST_TX_LENGTH;
		xhci->quirks |= XHCI_BROKEN_STREAMS;```
So XHCI_BROKEN_STREAMS propably adresses another issue (this "fix" could cause other problems with other devices, however the system freezes are fixed by disabling the streams).

**Comment by terencode** [comment]
Ok so is it related that I get occasional freeze when removing usb 3.0 devices like the T4U without shutting it down properly?

**Comment by Thoma5** [comment]
I'm not a expert myself, but I think this isn't related with this, but could be caused somewhere else by the driver too.

**Comment by terencode** [comment]
Ok I'm going to investigate myself and try to compile the kernel. Thank you for the help, issue closed as not related to the driver itself.
