### ISSUE TITLE
Ubuntu 16.10 with kernel 4.8.0-17 make fails

### ISSUE THREAD

**Issue by wolfland** [Grawp/rtl8812au_rtl8821au#30]
Ubuntu 16.10 with kernel 4.8.0-17 fails to build due to error:

It appears that the compiler is expecting "aborted" to be a pointer to struct and is instead getting
type bool:

‘struct cfg80211_scan_info *’ but argument is of type ‘bool {aka _Bool}’

I would be glad to help resolve this (as well as learn) if someone could enlighten me as to 
where to look for the referenced code. 

I assume that the ./include/net/cfg80211.h:4113:6 reference is to
linux kernel code which has changed and therefor the failure.

The driver was making/working fine in Ubuntu 16.04 LTS on kernel 4.4.0-38 so I assume
that the cfg80211 code has changed in the kernel unless I am doing something stupid
again(the first time I tried to build the driver on 16.04 it failed due to my having a "space" in
the directory name which caused the make to fail).

Here is the output from the failed make:

[4.3.20-make-failure.txt](https://github.com/Grawp/rtl8812au_rtl8821au/files/501233/4.3.20-make-failure.txt)

Thanks,

**Comment by wolfland** [comment]
After a bit of digging I finally found the code(haven't mucked about in the kernel code since
v 0.99a of the kernel).

Here is what I found out so far:

The "aborted" variable has been changed from a bool to struct cfg80211_scan_info:
/**
 * struct cfg80211_scan_info - information about completed scan
 * @scan_start_tsf: scan start time in terms of the TSF of the BSS that the
 *	wireless device that requested the scan is connected to. If this
 *	information is not available, this field is left zero.
 * @tsf_bssid: the BSSID according to which %scan_start_tsf is set.
 * @aborted: set to true if the scan was aborted for any reason,
 *	userspace will be notified of that
 */
struct cfg80211_scan_info {
	u64 scan_start_tsf;
	u8 tsf_bssid[ETH_ALEN] __aligned(2);
	bool aborted;

This will require the following to be changed:
core/rtw_mlme.c:inline void rtw_indicate_scan_done( _adapter *padapter, bool aborted)
core/rtw_mlme.c:	rtw_os_indicate_scan_done(padapter, aborted);
include/rtw_mlme.h:void rtw_indicate_scan_done( _adapter *padapter, bool aborted);
include/mlme_osdep.h:void rtw_os_indicate_scan_done( _adapter *padapter, bool aborted);
os_dep/linux/ioctl_cfg80211.c:void rtw_cfg80211_indicate_scan_done(_adapter *adapter, bool aborted)
os_dep/linux/ioctl_cfg80211.c:			cfg80211_scan_done(pwdev_priv->scan_request, aborted);
os_dep/linux/ioctl_cfg80211.h:void rtw_cfg80211_indicate_scan_done(_adapter *adapter, bool aborted);
os_dep/linux/mlme_linux.c:void rtw_os_indicate_scan_done( _adapter *padapter, bool aborted)
os_dep/linux/mlme_linux.c:	rtw_cfg80211_indicate_scan_done(padapter, aborted);

I assume that kernel => 4.8 checks will have to be added to ensure the changes do not break
the older kernel functionality.

This is about all I can tell without having some familiarity with the overall code.

I may take a run a coding this up but I have to get through my todo list first
which will be at least 2 or 3 weeks.

Thanks again,

**Comment by terencode** [comment]
Thank you for the report, I submitted a pull-request.

**Comment by wolfland** [comment]
I pulled the code from PR33 and it builds and has been working fine for the
past several days.

Thanks again

**Comment by terencode** [comment]
Ok I'll close mine then, PR33 is better, glad it's working :smile:

**Comment by libcg** [comment]
This should be fixed now, mind closing it?
